# Resume NER
## Extract Information from Resumes using NER (Named Entity Recognition)

### Part 1 - Data Exploration and preprocessing

#### Load the Dataset
The dataset we will be using is located in the dataset folder included in the project. Verify the data is available by executing the code cell below

In [1]:
import os
dataset_path = "./data/Entity Recognition in Resumes.json"
print("Path exists? {}".format(os.path.exists(dataset_path)))

Path exists? True

In [2]:
## use the "open" function to get a filehandle. 
with open(dataset_path,encoding="utf8") as f:
    ## use the filehandle to read all lines into an array of text lines. 
    lines = f.readlines()
    ## print how many lines were loaded
    print(len(lines))
    ## now print one resume/line to see how the resumes look in raw text form
    print("Sample resume:", lines[0])
    #TODO print sample resume

701
Sample resume: {"content": "Afreen Jamadar\nActive member of IIIT Committee in Third year\n\nSangli, Maharashtra - Email me on Indeed: indeed.com/r/Afreen-Jamadar/8baf379b705e37c6\n\nI wish to use my knowledge, skills and conceptual understanding to create excellent team\nenvironments and work consistently achieving organization objectives believes in taking initiative\nand work to excellence in my work.\n\nWORK EXPERIENCE\n\nActive member of IIIT Committee in Third year\n\nCisco Networking -  Kanpur, Uttar Pradesh\n\norganized by Techkriti IIT Kanpur and Azure Skynet.\nPERSONALLITY TRAITS:\n• Quick learning ability\n• hard working\n\nEDUCATION\n\nPG-DAC\n\nCDAC ACTS\n\n2017\n\nBachelor of Engg in Information Technology\n\nShivaji University Kolhapur -  Kolhapur, Maharashtra\n\n2016\n\nSKILLS\n\nDatabase (Less than 1 year), HTML (Less than 1 year), Linux. (Less than 1 year), MICROSOFT\nACCESS (Less than 1 year), MICROSOFT WINDOWS (Less than 1 year)\n\nADDITIONAL INFORMATION\n\nTECHNICAL SKILLS:\n\n• Programming Languages: C, C++, Java, .net, php.\n• Web Designing: HTML, XML\n• Operating Systems: Windows […] Windows Server 2003, Linux.\n• Database: MS Access, MS SQL Server 2008, Oracle 10g, MySql.\n\nhttps://www.indeed.com/r/Afreen-Jamadar/8baf379b705e37c6?isid=rex-download&ikw=download-top&co=IN","annotation":[{"label":["Email Address"],"points":[{"start":1155,"end":1198,"text":"indeed.com/r/Afreen-Jamadar/8baf379b705e37c6"}]},{"label":["Links"],"points":[{"start":1143,"end":1239,"text":"https://www.indeed.com/r/Afreen-Jamadar/8baf379b705e37c6?isid=rex-download&ikw=download-top&co=IN"}]},{"label":["Skills"],"points":[{"start":743,"end":1140,"text":"Database (Less than 1 year), HTML (Less than 1 year), Linux. (Less than 1 year), MICROSOFT\nACCESS (Less than 1 year), MICROSOFT WINDOWS (Less than 1 year)\n\nADDITIONAL INFORMATION\n\nTECHNICAL SKILLS:\n\n• Programming Languages: C, C++, Java, .net, php.\n• Web Designing: HTML, XML\n• Operating Systems: Windows […] Windows Server 2003, Linux.\n• Database: MS Access, MS SQL Server 2008, Oracle 10g, MySql."}]},{"label":["Graduation Year"],"points":[{"start":729,"end":732,"text":"2016"}]},{"label":["College Name"],"points":[{"start":675,"end":702,"text":"Shivaji University Kolhapur "}]},{"label":["Degree"],"points":[{"start":631,"end":672,"text":"Bachelor of Engg in Information Technology"}]},{"label":["Graduation Year"],"points":[{"start":625,"end":629,"text":"2017\n"}]},{"label":["College Name"],"points":[{"start":614,"end":622,"text":"CDAC ACTS"}]},{"label":["Degree"],"points":[{"start":606,"end":611,"text":"PG-DAC"}]},{"label":["Companies worked at"],"points":[{"start":438,"end":453,"text":"Cisco Networking"}]},{"label":["Email Address"],"points":[{"start":104,"end":147,"text":"indeed.com/r/Afreen-Jamadar/8baf379b705e37c6"}]},{"label":["Location"],"points":[{"start":62,"end":67,"text":"Sangli"}]},{"label":["Name"],"points":[{"start":0,"end":13,"text":"Afreen Jamadar"}]}],"extras":null,"metadata":{"first_done_at":1527844872000,"last_updated_at":1537724086000,"sec_taken":0,"last_updated_by":"BIQNZm4INNfvByMqkaVwVt6OZTv2","status":"done","evaluation":"CORRECT"}}

#### Convert the dataset to json

In [3]:
## import json module to load json strings
import json
## using a for loop or a list comprehension, cycle through all lines (loaded above) and convert them to dictionaries
## using json loads function. Make sure all converted resumes are stored in the 'all_resumes' array below  
all_resumes = [json.loads(line) for line in lines]
## select one resume to examine from the all_resumes list
resume = all_resumes[1]
print(resume)

{'content': 'Alok Khandai\nOperational Analyst (SQL DBA) Engineer - UNISYS\n\nBengaluru, Karnataka - Email me on Indeed: indeed.com/r/Alok-Khandai/5be849e443b8f467\n\n❖ Having 3.5 Years of IT experience in SQL Database Administration, System Analysis, Design,\nDevelopment & Support of MS SQL Servers in Production, Development environments &\nReplication and Cluster Server Environments.\n❖ Working Experience with relational database such as SQL.\n❖ Experience in Installation, Configuration, Maintenance and Administration of SQL Server.\n❖ Experience in upgrading SQL Server.\n❖ Good experience with implementing DR solution, High Availability of database servers using\nDatabase mirroring and replications and Log Shipping.\n❖ Experience in implementing SQL Server security and Object permissions like maintaining\nDatabase authentication modes, creation of users, configuring permissions and assigning roles\nto users.\n❖ Experience in creating Jobs, Alerts, SQL Mail Agent\n❖ Experience in performing integrity checks. Methods include configuring the database\nmaintenance plan wizard and DBCC utilities\n❖ Experience in using Performance Monitor, SQL Profiler and optimizing the queries, tracing long\nrunning queries and deadlocks.\n❖ Experience in applying patches and service packs to keep the database at current patch level.\n❖ Ability to manage own work and multitask to meet tight deadlines without losing sight of\npriorities..\n\nWilling to relocate to: Bengaluru, Karnataka\n\nWORK EXPERIENCE\n\nOperational Analyst (SQL DBA) Engineer\n\nUNISYS -  Bengaluru, Karnataka -\n\nJuly 2016 to Present\n\n❖ Having 3.5 Years of IT experience in SQL Database Administration, System Analysis, Design,\nDevelopment & Support of MS SQL Servers in Production, Development environments &\nReplication and Cluster Server Environments.\n❖ Working Experience with relational database such as SQL.\n❖ Experience in Installation, Configuration, Maintenance and Administration of SQL Server. \n❖ Experience in upgrading SQL Server.\n❖ Good experience with implementing DR solution, High Availability of database servers using\nDatabase mirroring and replications and Log Shipping.\n❖ Experience in implementing SQL Server security and Object permissions like maintaining\nDatabase authentication modes, creation of users, configuring permissions and assigning roles\nto users.\n\nDBA Support Analyst\n\nMicrosoft Corporation -  Redmond, WA -\n\nhttps://www.indeed.com/r/Alok-Khandai/5be849e443b8f467?isid=rex-download&ikw=download-top&co=IN\n\n\nJuly 2016 to Present\n\nClient Description:\nMicrosoft Corporation is an American public multinational corporation headquartered in\nRedmond, Washington, USA that develops, manufactures, licenses, and supports a wide range of\nproducts and services predominantly related to computing through its various product divisions.\n\nEnvironment:\nMicrosoft has E2E development and production environment of more than 25000 servers and\napplications. We are responsible for pro-active monitoring of all the servers and their jobs using\nmonitoring tools to reduce critical business impact by alerting respective peer teams. Microsoft\nService Enterprise an ITSM tools are used for ticketing and SharePoint portal is used to store all\ntechnical and process documentation.\n\nRoles and Responsibilities:\n• Responsible for Database support, troubleshooting, planning and migration. Resource planning\nand coordination for application migrations with project managers, application and web app\nteams. Project involved guidance and adherence to standardized procedures for planned data\ncenter consolidation for worldwide centers using in-house corporate and third party applications\nbased on SQL 2000 in upgrade project to SQL 2005.\n• Monitoring of database size and disk space in Production, Staging & Development environments\n• Performed installation of SQL Enterprise 2005 64bit version on Windows 2003 servers on\nEnterprise systems of clustered and standalone servers in enterprise Data Centers. Patch\napplications.\n• Failover cluster testing and resolution on HP servers as well as monitoring and backup reporting\nsetup with Microsoft Operations Manager and backup teams.\n• Working in Microsoft production environment which includes applications and servers.\n• Configured Transactional Replication and Log Shipping with SQL Server Management Studio as\nwell as basic account management and troubleshooting with connectivity, security and firewall\nissues.\n• Handling issues related to Server Availability, Performance.\n• Performed Production support and on Call duties\n• Conducted Performance Tuning using SQL Profiler and Windows Performance Monitor.\n• Worked with various business groups while developing their applications, assisting in database\ndesign, installing SQL Server clients, phasing from development to QA and to Production\nenvironment.\n\nPrevious Project\n❖ Project Title: Finance Support\n❖ Client: Costco Wholesale Corporation (USA)\n❖ Team size: 22\n❖ Role: DBA Support Analyst\n❖ Environment: Window 10\n\n(SQL DBA Analyst) Engineer\n\nHCL Technologies -  Bengaluru, Karnataka -\n\nNovember 2014 to July 2016\n\n〓 Performed server installation and configurations for SQL Server 2005 and SQL Server 2000.\n\n\n\n〓 Performed installation of SQL Server Service Packs\n〓 Upgraded databases from SQL Server 2000 to SQL Server 2005.\n〓 Scheduled Full and Transactional log backups for the user created and system databases in\nthe production environment using the Database Maintenance Plan Wizard.\n〓 Setup backup and restoration jobs for development and QA environments\n〓 Created transactional replication for the reporting applications.\n〓 Implemented disaster recovery solution at the remote site for the production databases using\nLog Shipping.\n〓 Used System monitor to find the bottlenecks in CPU, Disk I/O and memory devices and\nimproved the database server performance.\n〓 Used SQL Server Profiler to monitor and record database activities of particular users and\napplications.\n〓 Used DBCC commands to troubleshoot issues related to database consistency\n〓 Worked with various business groups while developing their applications, assisting in database\ndesign, installing SQL Server clients, phasing from development to QA and to Production\nenvironment\n\nMicrosoft Corporation -\n\nNovember 2014 to July 2016\n\nClient Description:\n\n❖ Costco Wholesale Corporation operates an international chain of membership warehouses,\nmainly under the "Costco Wholesale" name, that carry quality, brand name merchandise at\nsubstantially lower prices than are typically found at conventional wholesale or retail sources. The\nwarehouses are designed to help small-to-medium-sized businesses reduce costs in purchasing\nfor resale and for everyday business use. Individuals may also purchase for their personal needs.\n\n❖ Responsibilities:\n\n➢ Performed server installation and configurations for SQL Server 2005 and SQL Server 2000.\n➢ Performed installation of SQL Server Service Packs\n➢ Upgraded databases from SQL Server 2000 to SQL Server 2005.\n➢ Scheduled Full and Transactional log backups for the user created and system databases in\nthe production environment using the Database Maintenance Plan Wizard.\n➢ Setup backup and restoration jobs for development and QA environments\n➢ Created transactional replication for the reporting applications.\n➢ Implemented disaster recovery solution at the remote site for the production databases using\nLog Shipping.\n➢ Used System monitor to find the bottlenecks in CPU, Disk I/O and memory devices and improved\nthe database server performance.\n➢ Used SQL Server Profiler to monitor and record database activities of particular users and\napplications.\n➢ Used DBCC commands to troubleshoot issues related to database consistency\n➢ Worked with various business groups while developing their applications, assisting in database\ndesign, installing SQL Server clients, phasing from development to QA and to Production\nenvironment\n\n\n\nEDUCATION\n\nB.Tech in Computer Science and Engineering in CSE\n\nIndira Gandhi Institute Of Technology\n\n2012\n\nSKILLS\n\nDatabase (3 years), SQL (3 years), Sql Dba\n\nADDITIONAL INFORMATION\n\nTECHNICAL PROFICIENCY\n❖ Operating Environment: […] Windows95/98/XP/NT\n❖ Database Tool: SQL Management Studio (MSSQL), Business\nDevelopment Studio, Visual studio 2005\n❖ Database Language: SQL, PL/SQL\n❖ Ticket Tracking Tool: Service Now\n❖ Reporting Tools: MS Reporting Services, SAS\n❖ Languages: C, C++, PL/SQL', 'annotation': [{'label': ['Skills'], 'points': [{'start': 8098, 'end': 8383, 'text': '❖ Operating Environment: […] Windows95/98/XP/NT\n❖ Database Tool: SQL Management Studio (MSSQL), Business\nDevelopment Studio, Visual studio 2005\n❖ Database Language: SQL, PL/SQL\n❖ Ticket Tracking Tool: Service Now\n❖ Reporting Tools: MS Reporting Services, SAS\n❖ Languages: C, C++, PL/SQL'}]}, {'label': ['Skills'], 'points': [{'start': 8008, 'end': 8049, 'text': 'Database (3 years), SQL (3 years), Sql Dba'}]}, {'label': ['Graduation Year'], 'points': [{'start': 7994, 'end': 7997, 'text': '2012'}]}, {'label': ['College Name'], 'points': [{'start': 7955, 'end': 7991, 'text': 'Indira Gandhi Institute Of Technology'}]}, {'label': ['College Name'], 'points': [{'start': 7904, 'end': 7952, 'text': 'B.Tech in Computer Science and Engineering in CSE'}]}, {'label': ['Companies worked at'], 'points': [{'start': 6199, 'end': 6219, 'text': 'Microsoft Corporation'}]}, {'label': ['Location'], 'points': [{'start': 5016, 'end': 5024, 'text': 'Bengaluru'}]}, {'label': ['Companies worked at'], 'points': [{'start': 4996, 'end': 5011, 'text': 'HCL Technologies'}]}, {'label': ['Designation'], 'points': [{'start': 4969, 'end': 4983, 'text': 'SQL DBA Analyst'}]}, {'label': ['Designation'], 'points': [{'start': 4922, 'end': 4940, 'text': 'DBA Support Analyst'}]}, {'label': ['projects'], 'points': [{'start': 4836, 'end': 4851, 'text': ' Finance Support'}]}, {'label': ['Companies worked at'], 'points': [{'start': 2519, 'end': 2539, 'text': 'Microsoft Corporation'}]}, {'label': ['Email Address'], 'points': [{'start': 2391, 'end': 2432, 'text': 'indeed.com/r/Alok-Khandai/5be849e443b8f467'}]}, {'label': ['Companies worked at'], 'points': [{'start': 2339, 'end': 2359, 'text': 'Microsoft Corporation'}]}, {'label': ['Designation'], 'points': [{'start': 2318, 'end': 2336, 'text': 'DBA Support Analyst'}]}, {'label': ['Skills'], 'points': [{'start': 1607, 'end': 1658, 'text': 'SQL Database Administration, System Analysis, Design'}]}, {'label': ['Years of Experience'], 'points': [{'start': 1577, 'end': 1585, 'text': '3.5 Years'}]}, {'label': ['Location'], 'points': [{'start': 1522, 'end': 1530, 'text': 'Bengaluru'}]}, {'label': ['Companies worked at'], 'points': [{'start': 1512, 'end': 1517, 'text': 'UNISYS'}]}, {'label': ['Designation'], 'points': [{'start': 1472, 'end': 1509, 'text': 'Operational Analyst (SQL DBA) Engineer'}]}, {'label': ['Location'], 'points': [{'start': 1433, 'end': 1441, 'text': 'Bengaluru'}]}, {'label': ['Skills'], 'points': [{'start': 188, 'end': 239, 'text': 'SQL Database Administration, System Analysis, Design'}]}, {'label': ['Email Address'], 'points': [{'start': 105, 'end': 146, 'text': 'indeed.com/r/Alok-Khandai/5be849e443b8f467'}]}, {'label': ['Location'], 'points': [{'start': 62, 'end': 70, 'text': 'Bengaluru'}]}, {'label': ['Companies worked at'], 'points': [{'start': 54, 'end': 59, 'text': 'UNISYS'}]}, {'label': ['Designation'], 'points': [{'start': 13, 'end': 50, 'text': 'Operational Analyst (SQL DBA) Engineer'}]}, {'label': ['Name'], 'points': [{'start': 0, 'end': 11, 'text': 'Alok Khandai'}]}], 'extras': None, 'metadata': {'first_done_at': 1527845028000, 'last_updated_at': 1538662820000, 'sec_taken': 0, 'last_updated_by': 'BIQNZm4INNfvByMqkaVwVt6OZTv2', 'status': 'done', 'evaluation': 'CORRECT'}}

##### Explore the resume data structure

In [4]:
## explore keys in cv
print("keys and values in resume:")
## TODO print out the keys and values for the sample resume
for key, value in resume.items():
    print("key: {} value: {}".format(key, value))

keys and values in resume:
key: content value: Alok Khandai
Operational Analyst (SQL DBA) Engineer - UNISYS

Bengaluru, Karnataka - Email me on Indeed: indeed.com/r/Alok-Khandai/5be849e443b8f467

❖ Having 3.5 Years of IT experience in SQL Database Administration, System Analysis, Design,
Development & Support of MS SQL Servers in Production, Development environments &
Replication and Cluster Server Environments.
❖ Working Experience with relational database such as SQL.
❖ Experience in Installation, Configuration, Maintenance and Administration of SQL Server.
❖ Experience in upgrading SQL Server.
❖ Good experience with implementing DR solution, High Availability of database servers using
Database mirroring and replications and Log Shipping.
❖ Experience in implementing SQL Server security and Object permissions like maintaining
Database authentication modes, creation of users, configuring permissions and assigning roles
to users.
❖ Experience in creating Jobs, Alerts, SQL Mail Agent
❖ Experience in performing integrity checks. Methods include configuring the database
maintenance plan wizard and DBCC utilities
❖ Experience in using Performance Monitor, SQL Profiler and optimizing the queries, tracing long
running queries and deadlocks.
❖ Experience in applying patches and service packs to keep the database at current patch level.
❖ Ability to manage own work and multitask to meet tight deadlines without losing sight of
priorities..

Willing to relocate to: Bengaluru, Karnataka

WORK EXPERIENCE

Operational Analyst (SQL DBA) Engineer

UNISYS -  Bengaluru, Karnataka -

July 2016 to Present

❖ Having 3.5 Years of IT experience in SQL Database Administration, System Analysis, Design,
Development & Support of MS SQL Servers in Production, Development environments &
Replication and Cluster Server Environments.
❖ Working Experience with relational database such as SQL.
❖ Experience in Installation, Configuration, Maintenance and Administration of SQL Server.
❖ Experience in upgrading SQL Server.
❖ Good experience with implementing DR solution, High Availability of database servers using
Database mirroring and replications and Log Shipping.
❖ Experience in implementing SQL Server security and Object permissions like maintaining
Database authentication modes, creation of users, configuring permissions and assigning roles
to users.

DBA Support Analyst

Microsoft Corporation -  Redmond, WA -

https://www.indeed.com/r/Alok-Khandai/5be849e443b8f467?isid=rex-download&ikw=download-top&co=IN


July 2016 to Present

Client Description:
Microsoft Corporation is an American public multinational corporation headquartered in
Redmond, Washington, USA that develops, manufactures, licenses, and supports a wide range of
products and services predominantly related to computing through its various product divisions.

Environment:
Microsoft has E2E development and production environment of more than 25000 servers and
applications. We are responsible for pro-active monitoring of all the servers and their jobs using
monitoring tools to reduce critical business impact by alerting respective peer teams. Microsoft
Service Enterprise an ITSM tools are used for ticketing and SharePoint portal is used to store all
technical and process documentation.

Roles and Responsibilities:
• Responsible for Database support, troubleshooting, planning and migration. Resource planning
and coordination for application migrations with project managers, application and web app
teams. Project involved guidance and adherence to standardized procedures for planned data
center consolidation for worldwide centers using in-house corporate and third party applications
based on SQL 2000 in upgrade project to SQL 2005.
• Monitoring of database size and disk space in Production, Staging & Development environments
• Performed installation of SQL Enterprise 2005 64bit version on Windows 2003 servers on
Enterprise systems of clustered and standalone servers in enterprise Data Centers. Patch
applications.
• Failover cluster testing and resolution on HP servers as well as monitoring and backup reporting
setup with Microsoft Operations Manager and backup teams.
• Working in Microsoft production environment which includes applications and servers.
• Configured Transactional Replication and Log Shipping with SQL Server Management Studio as
well as basic account management and troubleshooting with connectivity, security and firewall
issues.
• Handling issues related to Server Availability, Performance.
• Performed Production support and on Call duties
• Conducted Performance Tuning using SQL Profiler and Windows Performance Monitor.
• Worked with various business groups while developing their applications, assisting in database
design, installing SQL Server clients, phasing from development to QA and to Production
environment.

Previous Project
❖ Project Title: Finance Support
❖ Client: Costco Wholesale Corporation (USA)
❖ Team size: 22
❖ Role: DBA Support Analyst
❖ Environment: Window 10

(SQL DBA Analyst) Engineer

HCL Technologies -  Bengaluru, Karnataka -

November 2014 to July 2016

〓 Performed server installation and configurations for SQL Server 2005 and SQL Server 2000.



〓 Performed installation of SQL Server Service Packs
〓 Upgraded databases from SQL Server 2000 to SQL Server 2005.
〓 Scheduled Full and Transactional log backups for the user created and system databases in
the production environment using the Database Maintenance Plan Wizard.
〓 Setup backup and restoration jobs for development and QA environments
〓 Created transactional replication for the reporting applications.
〓 Implemented disaster recovery solution at the remote site for the production databases using
Log Shipping.
〓 Used System monitor to find the bottlenecks in CPU, Disk I/O and memory devices and
improved the database server performance.
〓 Used SQL Server Profiler to monitor and record database activities of particular users and
applications.
〓 Used DBCC commands to troubleshoot issues related to database consistency
〓 Worked with various business groups while developing their applications, assisting in database
design, installing SQL Server clients, phasing from development to QA and to Production
environment

Microsoft Corporation -

November 2014 to July 2016

Client Description:

❖ Costco Wholesale Corporation operates an international chain of membership warehouses,
mainly under the "Costco Wholesale" name, that carry quality, brand name merchandise at
substantially lower prices than are typically found at conventional wholesale or retail sources. The
warehouses are designed to help small-to-medium-sized businesses reduce costs in purchasing
for resale and for everyday business use. Individuals may also purchase for their personal needs.

❖ Responsibilities:

➢ Performed server installation and configurations for SQL Server 2005 and SQL Server 2000.
➢ Performed installation of SQL Server Service Packs
➢ Upgraded databases from SQL Server 2000 to SQL Server 2005.
➢ Scheduled Full and Transactional log backups for the user created and system databases in
the production environment using the Database Maintenance Plan Wizard.
➢ Setup backup and restoration jobs for development and QA environments
➢ Created transactional replication for the reporting applications.
➢ Implemented disaster recovery solution at the remote site for the production databases using
Log Shipping.
➢ Used System monitor to find the bottlenecks in CPU, Disk I/O and memory devices and improved
the database server performance.
➢ Used SQL Server Profiler to monitor and record database activities of particular users and
applications.
➢ Used DBCC commands to troubleshoot issues related to database consistency
➢ Worked with various business groups while developing their applications, assisting in database
design, installing SQL Server clients, phasing from development to QA and to Production
environment



EDUCATION

B.Tech in Computer Science and Engineering in CSE

Indira Gandhi Institute Of Technology

2012

SKILLS

Database (3 years), SQL (3 years), Sql Dba

ADDITIONAL INFORMATION

TECHNICAL PROFICIENCY
❖ Operating Environment: […] Windows95/98/XP/NT
❖ Database Tool: SQL Management Studio (MSSQL), Business
Development Studio, Visual studio 2005
❖ Database Language: SQL, PL/SQL
❖ Ticket Tracking Tool: Service Now
❖ Reporting Tools: MS Reporting Services, SAS
❖ Languages: C, C++, PL/SQL
key: annotation value: [{'label': ['Skills'], 'points': [{'start': 8098, 'end': 8383, 'text': '❖ Operating Environment: […] Windows95/98/XP/NT\n❖ Database Tool: SQL Management Studio (MSSQL), Business\nDevelopment Studio, Visual studio 2005\n❖ Database Language: SQL, PL/SQL\n❖ Ticket Tracking Tool: Service Now\n❖ Reporting Tools: MS Reporting Services, SAS\n❖ Languages: C, C++, PL/SQL'}]}, {'label': ['Skills'], 'points': [{'start': 8008, 'end': 8049, 'text': 'Database (3 years), SQL (3 years), Sql Dba'}]}, {'label': ['Graduation Year'], 'points': [{'start': 7994, 'end': 7997, 'text': '2012'}]}, {'label': ['College Name'], 'points': [{'start': 7955, 'end': 7991, 'text': 'Indira Gandhi Institute Of Technology'}]}, {'label': ['College Name'], 'points': [{'start': 7904, 'end': 7952, 'text': 'B.Tech in Computer Science and Engineering in CSE'}]}, {'label': ['Companies worked at'], 'points': [{'start': 6199, 'end': 6219, 'text': 'Microsoft Corporation'}]}, {'label': ['Location'], 'points': [{'start': 5016, 'end': 5024, 'text': 'Bengaluru'}]}, {'label': ['Companies worked at'], 'points': [{'start': 4996, 'end': 5011, 'text': 'HCL Technologies'}]}, {'label': ['Designation'], 'points': [{'start': 4969, 'end': 4983, 'text': 'SQL DBA Analyst'}]}, {'label': ['Designation'], 'points': [{'start': 4922, 'end': 4940, 'text': 'DBA Support Analyst'}]}, {'label': ['projects'], 'points': [{'start': 4836, 'end': 4851, 'text': ' Finance Support'}]}, {'label': ['Companies worked at'], 'points': [{'start': 2519, 'end': 2539, 'text': 'Microsoft Corporation'}]}, {'label': ['Email Address'], 'points': [{'start': 2391, 'end': 2432, 'text': 'indeed.com/r/Alok-Khandai/5be849e443b8f467'}]}, {'label': ['Companies worked at'], 'points': [{'start': 2339, 'end': 2359, 'text': 'Microsoft Corporation'}]}, {'label': ['Designation'], 'points': [{'start': 2318, 'end': 2336, 'text': 'DBA Support Analyst'}]}, {'label': ['Skills'], 'points': [{'start': 1607, 'end': 1658, 'text': 'SQL Database Administration, System Analysis, Design'}]}, {'label': ['Years of Experience'], 'points': [{'start': 1577, 'end': 1585, 'text': '3.5 Years'}]}, {'label': ['Location'], 'points': [{'start': 1522, 'end': 1530, 'text': 'Bengaluru'}]}, {'label': ['Companies worked at'], 'points': [{'start': 1512, 'end': 1517, 'text': 'UNISYS'}]}, {'label': ['Designation'], 'points': [{'start': 1472, 'end': 1509, 'text': 'Operational Analyst (SQL DBA) Engineer'}]}, {'label': ['Location'], 'points': [{'start': 1433, 'end': 1441, 'text': 'Bengaluru'}]}, {'label': ['Skills'], 'points': [{'start': 188, 'end': 239, 'text': 'SQL Database Administration, System Analysis, Design'}]}, {'label': ['Email Address'], 'points': [{'start': 105, 'end': 146, 'text': 'indeed.com/r/Alok-Khandai/5be849e443b8f467'}]}, {'label': ['Location'], 'points': [{'start': 62, 'end': 70, 'text': 'Bengaluru'}]}, {'label': ['Companies worked at'], 'points': [{'start': 54, 'end': 59, 'text': 'UNISYS'}]}, {'label': ['Designation'], 'points': [{'start': 13, 'end': 50, 'text': 'Operational Analyst (SQL DBA) Engineer'}]}, {'label': ['Name'], 'points': [{'start': 0, 'end': 11, 'text': 'Alok Khandai'}]}]
key: extras value: None
key: metadata value: {'first_done_at': 1527845028000, 'last_updated_at': 1538662820000, 'sec_taken': 0, 'last_updated_by': 'BIQNZm4INNfvByMqkaVwVt6OZTv2', 'status': 'done', 'evaluation': 'CORRECT'}

In [5]:
## TODO print the resume text
print("resume content:")
print(resume["content"])
## TODO print the resume's list of entity annotations
print("resume entity list:")
print(resume["annotation"])

resume content:
Alok Khandai
Operational Analyst (SQL DBA) Engineer - UNISYS

Bengaluru, Karnataka - Email me on Indeed: indeed.com/r/Alok-Khandai/5be849e443b8f467

❖ Having 3.5 Years of IT experience in SQL Database Administration, System Analysis, Design,
Development & Support of MS SQL Servers in Production, Development environments &
Replication and Cluster Server Environments.
❖ Working Experience with relational database such as SQL.
❖ Experience in Installation, Configuration, Maintenance and Administration of SQL Server.
❖ Experience in upgrading SQL Server.
❖ Good experience with implementing DR solution, High Availability of database servers using
Database mirroring and replications and Log Shipping.
❖ Experience in implementing SQL Server security and Object permissions like maintaining
Database authentication modes, creation of users, configuring permissions and assigning roles
to users.
❖ Experience in creating Jobs, Alerts, SQL Mail Agent
❖ Experience in performing integrity checks. Methods include configuring the database
maintenance plan wizard and DBCC utilities
❖ Experience in using Performance Monitor, SQL Profiler and optimizing the queries, tracing long
running queries and deadlocks.
❖ Experience in applying patches and service packs to keep the database at current patch level.
❖ Ability to manage own work and multitask to meet tight deadlines without losing sight of
priorities..

Willing to relocate to: Bengaluru, Karnataka

WORK EXPERIENCE

Operational Analyst (SQL DBA) Engineer

UNISYS -  Bengaluru, Karnataka -

July 2016 to Present

❖ Having 3.5 Years of IT experience in SQL Database Administration, System Analysis, Design,
Development & Support of MS SQL Servers in Production, Development environments &
Replication and Cluster Server Environments.
❖ Working Experience with relational database such as SQL.
❖ Experience in Installation, Configuration, Maintenance and Administration of SQL Server.
❖ Experience in upgrading SQL Server.
❖ Good experience with implementing DR solution, High Availability of database servers using
Database mirroring and replications and Log Shipping.
❖ Experience in implementing SQL Server security and Object permissions like maintaining
Database authentication modes, creation of users, configuring permissions and assigning roles
to users.

DBA Support Analyst

Microsoft Corporation -  Redmond, WA -

https://www.indeed.com/r/Alok-Khandai/5be849e443b8f467?isid=rex-download&ikw=download-top&co=IN


July 2016 to Present

Client Description:
Microsoft Corporation is an American public multinational corporation headquartered in
Redmond, Washington, USA that develops, manufactures, licenses, and supports a wide range of
products and services predominantly related to computing through its various product divisions.

Environment:
Microsoft has E2E development and production environment of more than 25000 servers and
applications. We are responsible for pro-active monitoring of all the servers and their jobs using
monitoring tools to reduce critical business impact by alerting respective peer teams. Microsoft
Service Enterprise an ITSM tools are used for ticketing and SharePoint portal is used to store all
technical and process documentation.

Roles and Responsibilities:
• Responsible for Database support, troubleshooting, planning and migration. Resource planning
and coordination for application migrations with project managers, application and web app
teams. Project involved guidance and adherence to standardized procedures for planned data
center consolidation for worldwide centers using in-house corporate and third party applications
based on SQL 2000 in upgrade project to SQL 2005.
• Monitoring of database size and disk space in Production, Staging & Development environments
• Performed installation of SQL Enterprise 2005 64bit version on Windows 2003 servers on
Enterprise systems of clustered and standalone servers in enterprise Data Centers. Patch
applications.
• Failover cluster testing and resolution on HP servers as well as monitoring and backup reporting
setup with Microsoft Operations Manager and backup teams.
• Working in Microsoft production environment which includes applications and servers.
• Configured Transactional Replication and Log Shipping with SQL Server Management Studio as
well as basic account management and troubleshooting with connectivity, security and firewall
issues.
• Handling issues related to Server Availability, Performance.
• Performed Production support and on Call duties
• Conducted Performance Tuning using SQL Profiler and Windows Performance Monitor.
• Worked with various business groups while developing their applications, assisting in database
design, installing SQL Server clients, phasing from development to QA and to Production
environment.

Previous Project
❖ Project Title: Finance Support
❖ Client: Costco Wholesale Corporation (USA)
❖ Team size: 22
❖ Role: DBA Support Analyst
❖ Environment: Window 10

(SQL DBA Analyst) Engineer

HCL Technologies -  Bengaluru, Karnataka -

November 2014 to July 2016

〓 Performed server installation and configurations for SQL Server 2005 and SQL Server 2000.



〓 Performed installation of SQL Server Service Packs
〓 Upgraded databases from SQL Server 2000 to SQL Server 2005.
〓 Scheduled Full and Transactional log backups for the user created and system databases in
the production environment using the Database Maintenance Plan Wizard.
〓 Setup backup and restoration jobs for development and QA environments
〓 Created transactional replication for the reporting applications.
〓 Implemented disaster recovery solution at the remote site for the production databases using
Log Shipping.
〓 Used System monitor to find the bottlenecks in CPU, Disk I/O and memory devices and
improved the database server performance.
〓 Used SQL Server Profiler to monitor and record database activities of particular users and
applications.
〓 Used DBCC commands to troubleshoot issues related to database consistency
〓 Worked with various business groups while developing their applications, assisting in database
design, installing SQL Server clients, phasing from development to QA and to Production
environment

Microsoft Corporation -

November 2014 to July 2016

Client Description:

❖ Costco Wholesale Corporation operates an international chain of membership warehouses,
mainly under the "Costco Wholesale" name, that carry quality, brand name merchandise at
substantially lower prices than are typically found at conventional wholesale or retail sources. The
warehouses are designed to help small-to-medium-sized businesses reduce costs in purchasing
for resale and for everyday business use. Individuals may also purchase for their personal needs.

❖ Responsibilities:

➢ Performed server installation and configurations for SQL Server 2005 and SQL Server 2000.
➢ Performed installation of SQL Server Service Packs
➢ Upgraded databases from SQL Server 2000 to SQL Server 2005.
➢ Scheduled Full and Transactional log backups for the user created and system databases in
the production environment using the Database Maintenance Plan Wizard.
➢ Setup backup and restoration jobs for development and QA environments
➢ Created transactional replication for the reporting applications.
➢ Implemented disaster recovery solution at the remote site for the production databases using
Log Shipping.
➢ Used System monitor to find the bottlenecks in CPU, Disk I/O and memory devices and improved
the database server performance.
➢ Used SQL Server Profiler to monitor and record database activities of particular users and
applications.
➢ Used DBCC commands to troubleshoot issues related to database consistency
➢ Worked with various business groups while developing their applications, assisting in database
design, installing SQL Server clients, phasing from development to QA and to Production
environment



EDUCATION

B.Tech in Computer Science and Engineering in CSE

Indira Gandhi Institute Of Technology

2012

SKILLS

Database (3 years), SQL (3 years), Sql Dba

ADDITIONAL INFORMATION

TECHNICAL PROFICIENCY
❖ Operating Environment: […] Windows95/98/XP/NT
❖ Database Tool: SQL Management Studio (MSSQL), Business
Development Studio, Visual studio 2005
❖ Database Language: SQL, PL/SQL
❖ Ticket Tracking Tool: Service Now
❖ Reporting Tools: MS Reporting Services, SAS
❖ Languages: C, C++, PL/SQL
resume entity list:
[{'label': ['Skills'], 'points': [{'start': 8098, 'end': 8383, 'text': '❖ Operating Environment: […] Windows95/98/XP/NT\n❖ Database Tool: SQL Management Studio (MSSQL), Business\nDevelopment Studio, Visual studio 2005\n❖ Database Language: SQL, PL/SQL\n❖ Ticket Tracking Tool: Service Now\n❖ Reporting Tools: MS Reporting Services, SAS\n❖ Languages: C, C++, PL/SQL'}]}, {'label': ['Skills'], 'points': [{'start': 8008, 'end': 8049, 'text': 'Database (3 years), SQL (3 years), Sql Dba'}]}, {'label': ['Graduation Year'], 'points': [{'start': 7994, 'end': 7997, 'text': '2012'}]}, {'label': ['College Name'], 'points': [{'start': 7955, 'end': 7991, 'text': 'Indira Gandhi Institute Of Technology'}]}, {'label': ['College Name'], 'points': [{'start': 7904, 'end': 7952, 'text': 'B.Tech in Computer Science and Engineering in CSE'}]}, {'label': ['Companies worked at'], 'points': [{'start': 6199, 'end': 6219, 'text': 'Microsoft Corporation'}]}, {'label': ['Location'], 'points': [{'start': 5016, 'end': 5024, 'text': 'Bengaluru'}]}, {'label': ['Companies worked at'], 'points': [{'start': 4996, 'end': 5011, 'text': 'HCL Technologies'}]}, {'label': ['Designation'], 'points': [{'start': 4969, 'end': 4983, 'text': 'SQL DBA Analyst'}]}, {'label': ['Designation'], 'points': [{'start': 4922, 'end': 4940, 'text': 'DBA Support Analyst'}]}, {'label': ['projects'], 'points': [{'start': 4836, 'end': 4851, 'text': ' Finance Support'}]}, {'label': ['Companies worked at'], 'points': [{'start': 2519, 'end': 2539, 'text': 'Microsoft Corporation'}]}, {'label': ['Email Address'], 'points': [{'start': 2391, 'end': 2432, 'text': 'indeed.com/r/Alok-Khandai/5be849e443b8f467'}]}, {'label': ['Companies worked at'], 'points': [{'start': 2339, 'end': 2359, 'text': 'Microsoft Corporation'}]}, {'label': ['Designation'], 'points': [{'start': 2318, 'end': 2336, 'text': 'DBA Support Analyst'}]}, {'label': ['Skills'], 'points': [{'start': 1607, 'end': 1658, 'text': 'SQL Database Administration, System Analysis, Design'}]}, {'label': ['Years of Experience'], 'points': [{'start': 1577, 'end': 1585, 'text': '3.5 Years'}]}, {'label': ['Location'], 'points': [{'start': 1522, 'end': 1530, 'text': 'Bengaluru'}]}, {'label': ['Companies worked at'], 'points': [{'start': 1512, 'end': 1517, 'text': 'UNISYS'}]}, {'label': ['Designation'], 'points': [{'start': 1472, 'end': 1509, 'text': 'Operational Analyst (SQL DBA) Engineer'}]}, {'label': ['Location'], 'points': [{'start': 1433, 'end': 1441, 'text': 'Bengaluru'}]}, {'label': ['Skills'], 'points': [{'start': 188, 'end': 239, 'text': 'SQL Database Administration, System Analysis, Design'}]}, {'label': ['Email Address'], 'points': [{'start': 105, 'end': 146, 'text': 'indeed.com/r/Alok-Khandai/5be849e443b8f467'}]}, {'label': ['Location'], 'points': [{'start': 62, 'end': 70, 'text': 'Bengaluru'}]}, {'label': ['Companies worked at'], 'points': [{'start': 54, 'end': 59, 'text': 'UNISYS'}]}, {'label': ['Designation'], 'points': [{'start': 13, 'end': 50, 'text': 'Operational Analyst (SQL DBA) Engineer'}]}, {'label': ['Name'], 'points': [{'start': 0, 'end': 11, 'text': 'Alok Khandai'}]}]

##### Explore the list of entity labels

In [6]:
## explore entity list
##TODO print out each key and each value for each entity in the entities list
for entity in resume["annotation"]:
    print("Entity")
    for key, value in entity.items():
        print("key: {} value: {}".format(key, value))
        
print(resume["annotation"][1]['points'])
print(type(resume["annotation"][1]['points']))

Entity
key: label value: ['Skills']
key: points value: [{'start': 8098, 'end': 8383, 'text': '❖ Operating Environment: […] Windows95/98/XP/NT\n❖ Database Tool: SQL Management Studio (MSSQL), Business\nDevelopment Studio, Visual studio 2005\n❖ Database Language: SQL, PL/SQL\n❖ Ticket Tracking Tool: Service Now\n❖ Reporting Tools: MS Reporting Services, SAS\n❖ Languages: C, C++, PL/SQL'}]
Entity
key: label value: ['Skills']
key: points value: [{'start': 8008, 'end': 8049, 'text': 'Database (3 years), SQL (3 years), Sql Dba'}]
Entity
key: label value: ['Graduation Year']
key: points value: [{'start': 7994, 'end': 7997, 'text': '2012'}]
Entity
key: label value: ['College Name']
key: points value: [{'start': 7955, 'end': 7991, 'text': 'Indira Gandhi Institute Of Technology'}]
Entity
key: label value: ['College Name']
key: points value: [{'start': 7904, 'end': 7952, 'text': 'B.Tech in Computer Science and Engineering in CSE'}]
Entity
key: label value: ['Companies worked at']
key: points value: [{'start': 6199, 'end': 6219, 'text': 'Microsoft Corporation'}]
Entity
key: label value: ['Location']
key: points value: [{'start': 5016, 'end': 5024, 'text': 'Bengaluru'}]
Entity
key: label value: ['Companies worked at']
key: points value: [{'start': 4996, 'end': 5011, 'text': 'HCL Technologies'}]
Entity
key: label value: ['Designation']
key: points value: [{'start': 4969, 'end': 4983, 'text': 'SQL DBA Analyst'}]
Entity
key: label value: ['Designation']
key: points value: [{'start': 4922, 'end': 4940, 'text': 'DBA Support Analyst'}]
Entity
key: label value: ['projects']
key: points value: [{'start': 4836, 'end': 4851, 'text': ' Finance Support'}]
Entity
key: label value: ['Companies worked at']
key: points value: [{'start': 2519, 'end': 2539, 'text': 'Microsoft Corporation'}]
Entity
key: label value: ['Email Address']
key: points value: [{'start': 2391, 'end': 2432, 'text': 'indeed.com/r/Alok-Khandai/5be849e443b8f467'}]
Entity
key: label value: ['Companies worked at']
key: points value: [{'start': 2339, 'end': 2359, 'text': 'Microsoft Corporation'}]
Entity
key: label value: ['Designation']
key: points value: [{'start': 2318, 'end': 2336, 'text': 'DBA Support Analyst'}]
Entity
key: label value: ['Skills']
key: points value: [{'start': 1607, 'end': 1658, 'text': 'SQL Database Administration, System Analysis, Design'}]
Entity
key: label value: ['Years of Experience']
key: points value: [{'start': 1577, 'end': 1585, 'text': '3.5 Years'}]
Entity
key: label value: ['Location']
key: points value: [{'start': 1522, 'end': 1530, 'text': 'Bengaluru'}]
Entity
key: label value: ['Companies worked at']
key: points value: [{'start': 1512, 'end': 1517, 'text': 'UNISYS'}]
Entity
key: label value: ['Designation']
key: points value: [{'start': 1472, 'end': 1509, 'text': 'Operational Analyst (SQL DBA) Engineer'}]
Entity
key: label value: ['Location']
key: points value: [{'start': 1433, 'end': 1441, 'text': 'Bengaluru'}]
Entity
key: label value: ['Skills']
key: points value: [{'start': 188, 'end': 239, 'text': 'SQL Database Administration, System Analysis, Design'}]
Entity
key: label value: ['Email Address']
key: points value: [{'start': 105, 'end': 146, 'text': 'indeed.com/r/Alok-Khandai/5be849e443b8f467'}]
Entity
key: label value: ['Location']
key: points value: [{'start': 62, 'end': 70, 'text': 'Bengaluru'}]
Entity
key: label value: ['Companies worked at']
key: points value: [{'start': 54, 'end': 59, 'text': 'UNISYS'}]
Entity
key: label value: ['Designation']
key: points value: [{'start': 13, 'end': 50, 'text': 'Operational Analyst (SQL DBA) Engineer'}]
Entity
key: label value: ['Name']
key: points value: [{'start': 0, 'end': 11, 'text': 'Alok Khandai'}]
[{'start': 8008, 'end': 8049, 'text': 'Database (3 years), SQL (3 years), Sql Dba'}]
<class 'list'>

##### Convert  data to "spacy" offset format
1. Use the provided data conversion function
2. Convert the data with that function, storing the results in a variable
3. Inspect the converted data

In [7]:
## data conversion method
def convert_data(data):
    """
    Creates NER training data in Spacy format from JSON dataset
    Outputs the Spacy training data which can be used for Spacy training.
    """
    text = data['content']
    entities = []
    if data['annotation'] is not None:
        for annotation in data['annotation']:
            # only a single point in text annotation.
            point = annotation['points'][0]
            labels = annotation['label']
            # handle both list of labels or a single label.
            if not isinstance(labels, list):
                labels = [labels]
            for label in labels:
                # dataturks indices are both inclusive [start, end] but spacy is not [start, end)
                entities.append((point['start'], point['end'] + 1, label))
    return (text, {"entities": entities})
   
## TODO using a loop or list comprehension, convert each resume in all_resumes using the convert function above, storing the result
converted_resumes = [convert_data(res) for res in all_resumes]
## TODO print the number of resumes in converted resumes 
print(len(converted_resumes))
print(converted_resumes[1])
print(type(converted_resumes[1]))

701
('Alok Khandai\nOperational Analyst (SQL DBA) Engineer - UNISYS\n\nBengaluru, Karnataka - Email me on Indeed: indeed.com/r/Alok-Khandai/5be849e443b8f467\n\n❖ Having 3.5 Years of IT experience in SQL Database Administration, System Analysis, Design,\nDevelopment & Support of MS SQL Servers in Production, Development environments &\nReplication and Cluster Server Environments.\n❖ Working Experience with relational database such as SQL.\n❖ Experience in Installation, Configuration, Maintenance and Administration of SQL Server.\n❖ Experience in upgrading SQL Server.\n❖ Good experience with implementing DR solution, High Availability of database servers using\nDatabase mirroring and replications and Log Shipping.\n❖ Experience in implementing SQL Server security and Object permissions like maintaining\nDatabase authentication modes, creation of users, configuring permissions and assigning roles\nto users.\n❖ Experience in creating Jobs, Alerts, SQL Mail Agent\n❖ Experience in performing integrity checks. Methods include configuring the database\nmaintenance plan wizard and DBCC utilities\n❖ Experience in using Performance Monitor, SQL Profiler and optimizing the queries, tracing long\nrunning queries and deadlocks.\n❖ Experience in applying patches and service packs to keep the database at current patch level.\n❖ Ability to manage own work and multitask to meet tight deadlines without losing sight of\npriorities..\n\nWilling to relocate to: Bengaluru, Karnataka\n\nWORK EXPERIENCE\n\nOperational Analyst (SQL DBA) Engineer\n\nUNISYS -  Bengaluru, Karnataka -\n\nJuly 2016 to Present\n\n❖ Having 3.5 Years of IT experience in SQL Database Administration, System Analysis, Design,\nDevelopment & Support of MS SQL Servers in Production, Development environments &\nReplication and Cluster Server Environments.\n❖ Working Experience with relational database such as SQL.\n❖ Experience in Installation, Configuration, Maintenance and Administration of SQL Server. \n❖ Experience in upgrading SQL Server.\n❖ Good experience with implementing DR solution, High Availability of database servers using\nDatabase mirroring and replications and Log Shipping.\n❖ Experience in implementing SQL Server security and Object permissions like maintaining\nDatabase authentication modes, creation of users, configuring permissions and assigning roles\nto users.\n\nDBA Support Analyst\n\nMicrosoft Corporation -  Redmond, WA -\n\nhttps://www.indeed.com/r/Alok-Khandai/5be849e443b8f467?isid=rex-download&ikw=download-top&co=IN\n\n\nJuly 2016 to Present\n\nClient Description:\nMicrosoft Corporation is an American public multinational corporation headquartered in\nRedmond, Washington, USA that develops, manufactures, licenses, and supports a wide range of\nproducts and services predominantly related to computing through its various product divisions.\n\nEnvironment:\nMicrosoft has E2E development and production environment of more than 25000 servers and\napplications. We are responsible for pro-active monitoring of all the servers and their jobs using\nmonitoring tools to reduce critical business impact by alerting respective peer teams. Microsoft\nService Enterprise an ITSM tools are used for ticketing and SharePoint portal is used to store all\ntechnical and process documentation.\n\nRoles and Responsibilities:\n• Responsible for Database support, troubleshooting, planning and migration. Resource planning\nand coordination for application migrations with project managers, application and web app\nteams. Project involved guidance and adherence to standardized procedures for planned data\ncenter consolidation for worldwide centers using in-house corporate and third party applications\nbased on SQL 2000 in upgrade project to SQL 2005.\n• Monitoring of database size and disk space in Production, Staging & Development environments\n• Performed installation of SQL Enterprise 2005 64bit version on Windows 2003 servers on\nEnterprise systems of clustered and standalone servers in enterprise Data Centers. Patch\napplications.\n• Failover cluster testing and resolution on HP servers as well as monitoring and backup reporting\nsetup with Microsoft Operations Manager and backup teams.\n• Working in Microsoft production environment which includes applications and servers.\n• Configured Transactional Replication and Log Shipping with SQL Server Management Studio as\nwell as basic account management and troubleshooting with connectivity, security and firewall\nissues.\n• Handling issues related to Server Availability, Performance.\n• Performed Production support and on Call duties\n• Conducted Performance Tuning using SQL Profiler and Windows Performance Monitor.\n• Worked with various business groups while developing their applications, assisting in database\ndesign, installing SQL Server clients, phasing from development to QA and to Production\nenvironment.\n\nPrevious Project\n❖ Project Title: Finance Support\n❖ Client: Costco Wholesale Corporation (USA)\n❖ Team size: 22\n❖ Role: DBA Support Analyst\n❖ Environment: Window 10\n\n(SQL DBA Analyst) Engineer\n\nHCL Technologies -  Bengaluru, Karnataka -\n\nNovember 2014 to July 2016\n\n〓 Performed server installation and configurations for SQL Server 2005 and SQL Server 2000.\n\n\n\n〓 Performed installation of SQL Server Service Packs\n〓 Upgraded databases from SQL Server 2000 to SQL Server 2005.\n〓 Scheduled Full and Transactional log backups for the user created and system databases in\nthe production environment using the Database Maintenance Plan Wizard.\n〓 Setup backup and restoration jobs for development and QA environments\n〓 Created transactional replication for the reporting applications.\n〓 Implemented disaster recovery solution at the remote site for the production databases using\nLog Shipping.\n〓 Used System monitor to find the bottlenecks in CPU, Disk I/O and memory devices and\nimproved the database server performance.\n〓 Used SQL Server Profiler to monitor and record database activities of particular users and\napplications.\n〓 Used DBCC commands to troubleshoot issues related to database consistency\n〓 Worked with various business groups while developing their applications, assisting in database\ndesign, installing SQL Server clients, phasing from development to QA and to Production\nenvironment\n\nMicrosoft Corporation -\n\nNovember 2014 to July 2016\n\nClient Description:\n\n❖ Costco Wholesale Corporation operates an international chain of membership warehouses,\nmainly under the "Costco Wholesale" name, that carry quality, brand name merchandise at\nsubstantially lower prices than are typically found at conventional wholesale or retail sources. The\nwarehouses are designed to help small-to-medium-sized businesses reduce costs in purchasing\nfor resale and for everyday business use. Individuals may also purchase for their personal needs.\n\n❖ Responsibilities:\n\n➢ Performed server installation and configurations for SQL Server 2005 and SQL Server 2000.\n➢ Performed installation of SQL Server Service Packs\n➢ Upgraded databases from SQL Server 2000 to SQL Server 2005.\n➢ Scheduled Full and Transactional log backups for the user created and system databases in\nthe production environment using the Database Maintenance Plan Wizard.\n➢ Setup backup and restoration jobs for development and QA environments\n➢ Created transactional replication for the reporting applications.\n➢ Implemented disaster recovery solution at the remote site for the production databases using\nLog Shipping.\n➢ Used System monitor to find the bottlenecks in CPU, Disk I/O and memory devices and improved\nthe database server performance.\n➢ Used SQL Server Profiler to monitor and record database activities of particular users and\napplications.\n➢ Used DBCC commands to troubleshoot issues related to database consistency\n➢ Worked with various business groups while developing their applications, assisting in database\ndesign, installing SQL Server clients, phasing from development to QA and to Production\nenvironment\n\n\n\nEDUCATION\n\nB.Tech in Computer Science and Engineering in CSE\n\nIndira Gandhi Institute Of Technology\n\n2012\n\nSKILLS\n\nDatabase (3 years), SQL (3 years), Sql Dba\n\nADDITIONAL INFORMATION\n\nTECHNICAL PROFICIENCY\n❖ Operating Environment: […] Windows95/98/XP/NT\n❖ Database Tool: SQL Management Studio (MSSQL), Business\nDevelopment Studio, Visual studio 2005\n❖ Database Language: SQL, PL/SQL\n❖ Ticket Tracking Tool: Service Now\n❖ Reporting Tools: MS Reporting Services, SAS\n❖ Languages: C, C++, PL/SQL', {'entities': [(8098, 8384, 'Skills'), (8008, 8050, 'Skills'), (7994, 7998, 'Graduation Year'), (7955, 7992, 'College Name'), (7904, 7953, 'College Name'), (6199, 6220, 'Companies worked at'), (5016, 5025, 'Location'), (4996, 5012, 'Companies worked at'), (4969, 4984, 'Designation'), (4922, 4941, 'Designation'), (4836, 4852, 'projects'), (2519, 2540, 'Companies worked at'), (2391, 2433, 'Email Address'), (2339, 2360, 'Companies worked at'), (2318, 2337, 'Designation'), (1607, 1659, 'Skills'), (1577, 1586, 'Years of Experience'), (1522, 1531, 'Location'), (1512, 1518, 'Companies worked at'), (1472, 1510, 'Designation'), (1433, 1442, 'Location'), (188, 240, 'Skills'), (105, 147, 'Email Address'), (62, 71, 'Location'), (54, 60, 'Companies worked at'), (13, 51, 'Designation'), (0, 12, 'Name')]})
<class 'tuple'>

##### filter out resumes without annotations
A few of the resumes have an empty entity list. We want to filter these resumes out of our data before continuing. We will do the following:
1. cycle through all resumes using for loop or list comprehension
2. for each resume, if the resume has no labled entities, ignore it. Otherwise save it to new resume list

In [8]:
## TODO filter out resumes where resume entities list is None (you can do this in a one-line list comprehension)
## sove to converted_resumes variable
converted_resumes =  [res for res in converted_resumes if len(res[1]["entities"])>0]
## TODO print length of new filtered converted_resumes.  
print(len(converted_resumes))

690

##### Print all entities for one converted resume
1. Store one converted resume in the 'converted_resume' variable
2. Find the entity list in the converted_resume
3. Cycle through the entities, and - using the start and end index - print the label of the entity and the value of the entity. This will be the text substring pointed to by the start and end index

In [9]:
## store one resume in the variable
converted_resume = converted_resumes[1]
## find text content and store in variable
text = converted_resume[0]
## find the entities list and store in variable
entities_list = converted_resume[1]
## TODO for each entity, print the label, and the text (text content substring pointed to by start and end index)
for entity in entities_list["entities"]:
    print("label: {}, text: {}".format(entity[2], text[entity[0]:entity[1]]))

label: Skills, text: ❖ Operating Environment: […] Windows95/98/XP/NT
❖ Database Tool: SQL Management Studio (MSSQL), Business
Development Studio, Visual studio 2005
❖ Database Language: SQL, PL/SQL
❖ Ticket Tracking Tool: Service Now
❖ Reporting Tools: MS Reporting Services, SAS
❖ Languages: C, C++, PL/SQL
label: Skills, text: Database (3 years), SQL (3 years), Sql Dba
label: Graduation Year, text: 2012
label: College Name, text: Indira Gandhi Institute Of Technology
label: College Name, text: B.Tech in Computer Science and Engineering in CSE
label: Companies worked at, text: Microsoft Corporation
label: Location, text: Bengaluru
label: Companies worked at, text: HCL Technologies
label: Designation, text: SQL DBA Analyst
label: Designation, text: DBA Support Analyst
label: projects, text:  Finance Support
label: Companies worked at, text: Microsoft Corporation
label: Email Address, text: indeed.com/r/Alok-Khandai/5be849e443b8f467
label: Companies worked at, text: Microsoft Corporation
label: Designation, text: DBA Support Analyst
label: Skills, text: SQL Database Administration, System Analysis, Design
label: Years of Experience, text: 3.5 Years
label: Location, text: Bengaluru
label: Companies worked at, text: UNISYS
label: Designation, text: Operational Analyst (SQL DBA) Engineer
label: Location, text: Bengaluru
label: Skills, text: SQL Database Administration, System Analysis, Design
label: Email Address, text: indeed.com/r/Alok-Khandai/5be849e443b8f467
label: Location, text: Bengaluru
label: Companies worked at, text: UNISYS
label: Designation, text: Operational Analyst (SQL DBA) Engineer
label: Name, text: Alok Khandai

##### Collect unique labels of all entities in dataset

In [10]:
## collect names of all entities in complete resume dataset
all_labels = list()
for res in converted_resumes:
    ## entity list of res
    entity_list = res[1]["entities"][0]
    #print(entity_list[2])
    all_labels.append(entity_list[2])
    ## TODO extend all_labels with labels of entities 
    ##all_labels.           
## TODO all_labels is not yet unique. Make the list a set of unique values
# print(all_labels)
unique_labels = set(all_labels)
## Print unique entity labels
print("Entity labels: ",unique_labels)

Entity labels:  {'projects', 'links', 'Skills', 'Email Address', 'Graduation Year', 'Links', 'Rewards and Achievements', 'College Name', 'UNKNOWN', 'Designation', 'state', 'College', 'Years of Experience', 'Companies worked at', 'Degree', 'Can Relocate to', 'Location', 'Name'}

##### Validate entities

In [11]:
## TODO store entity label names for the entities you want to work with in an array 
chosen_entity_label = ["Skills", "Years of Experience", "Designation", "Degree", "College Name"]
## for each chosen entity label, count how many documents have a labeled entity for that label, and how many labeled entities total there are 
## for that entity
for chosen in chosen_entity_label:
    found_docs_with_entity = 0
    entity_count = 0
    for resume in converted_resumes:
        entity_list = resume[1]["entities"]
        _,_,labels = zip(*entity_list)
        if chosen in labels:
            found_docs_with_entity+=1
            entity_count+=len([l for l in labels if l == chosen])
    print("Docs with {}: {}".format(chosen,found_docs_with_entity))
    print("Total count of {}: {}".format(chosen,entity_count))

Docs with Skills: 536
Total count of Skills: 2152
Docs with Years of Experience: 217
Total count of Years of Experience: 623
Docs with Designation: 650
Total count of Designation: 2842
Docs with Degree: 606
Total count of Degree: 1012
Docs with College Name: 497
Total count of College Name: 1160

##### Save converted data for later use

In [113]:
converted_resumes_path = "./data/converted_resumes.json"
##TODO save converted resumes to path using "open" and json's "dump" function. 
with open(converted_resumes_path, 'w') as outfile:
    json.dump(converted_resumes, outfile)